version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  # Frontend npm
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
    ignore:
      - dependency-name: "@hey-api/openapi-ts"
        update-types: ["version-update:semver-major"]
