"""add switch model

Revision ID: 65f8c8c47fe3
Revises: e2412789c190
Create Date: 2024-06-02 15:46:05.970902

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '65f8c8c47fe3'
down_revision = 'e2412789c190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('site', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=False)
    op.create_index(op.f('ix_group_site'), 'group', ['site'], unique=False)
    op.create_table('interface',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vlan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duplex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('speed', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('port', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('native_vlan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('allowed_vlan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('allowed_vlan_add', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interface_port'), 'interface', ['port'], unique=False)
    op.create_index(op.f('ix_interface_switch_id'), 'interface', ['switch_id'], unique=False)
    op.create_table('switch',
    sa.Column('ipaddress', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('groups', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('os_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('more_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_switch_hostname'), 'switch', ['hostname'], unique=True)
    op.create_table('arp',
    sa.Column('interface', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mac', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['switch_id'], ['switch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arp_ip'), 'arp', ['ip'], unique=False)
    op.create_table('ipinterface',
    sa.Column('interface', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ipv6', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipv4', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['switch_id'], ['switch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipinterface_ipv4'), 'ipinterface', ['ipv4'], unique=False)
    op.create_table('macaddress',
    sa.Column('interface', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vlan', sa.Integer(), nullable=True),
    sa.Column('static', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('moves', sa.Integer(), nullable=True),
    sa.Column('last_move', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['switch_id'], ['switch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macaddress_mac'), 'macaddress', ['mac'], unique=False)
    op.add_column('item', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('item', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'updated_at')
    op.drop_column('item', 'created_at')
    op.drop_index(op.f('ix_macaddress_mac'), table_name='macaddress')
    op.drop_table('macaddress')
    op.drop_index(op.f('ix_ipinterface_ipv4'), table_name='ipinterface')
    op.drop_table('ipinterface')
    op.drop_index(op.f('ix_arp_ip'), table_name='arp')
    op.drop_table('arp')
    op.drop_index(op.f('ix_switch_hostname'), table_name='switch')
    op.drop_table('switch')
    op.drop_index(op.f('ix_interface_switch_id'), table_name='interface')
    op.drop_index(op.f('ix_interface_port'), table_name='interface')
    op.drop_table('interface')
    op.drop_index(op.f('ix_group_site'), table_name='group')
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
