"""add credentials model

Revision ID: f0418d9eea16
Revises: 65f8c8c47fe3
Create Date: 2024-06-19 04:39:55.492272

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f0418d9eea16'
down_revision = '65f8c8c47fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential',
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('private_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_username'), 'credential', ['username'], unique=False)
    op.add_column('switch', sa.Column('credential_id', sa.Integer(), nullable=True))
    op.add_column('switch', sa.Column('port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('switch', 'port')
    op.drop_column('switch', 'credential_id')
    op.drop_index(op.f('ix_credential_username'), table_name='credential')
    op.drop_table('credential')
    # ### end Alembic commands ###
