/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSwitchesRouteImport } from './routes/_layout/switches'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutMac_addressesRouteImport } from './routes/_layout/mac_addresses'
import { Route as LayoutLogsRouteImport } from './routes/_layout/logs'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutIp_interfacesRouteImport } from './routes/_layout/ip_interfaces'
import { Route as LayoutInterfacesRouteImport } from './routes/_layout/interfaces'
import { Route as LayoutGroupsRouteImport } from './routes/_layout/groups'
import { Route as LayoutGroup_configRouteImport } from './routes/_layout/group_config'
import { Route as LayoutCredentialsRouteImport } from './routes/_layout/credentials'
import { Route as LayoutArpsRouteImport } from './routes/_layout/arps'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSwitchesRoute = LayoutSwitchesRouteImport.update({
  id: '/switches',
  path: '/switches',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMac_addressesRoute = LayoutMac_addressesRouteImport.update({
  id: '/mac_addresses',
  path: '/mac_addresses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLogsRoute = LayoutLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIp_interfacesRoute = LayoutIp_interfacesRouteImport.update({
  id: '/ip_interfaces',
  path: '/ip_interfaces',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInterfacesRoute = LayoutInterfacesRouteImport.update({
  id: '/interfaces',
  path: '/interfaces',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsRoute = LayoutGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroup_configRoute = LayoutGroup_configRouteImport.update({
  id: '/group_config',
  path: '/group_config',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCredentialsRoute = LayoutCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutArpsRoute = LayoutArpsRouteImport.update({
  id: '/arps',
  path: '/arps',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof LayoutAdminRoute
  '/arps': typeof LayoutArpsRoute
  '/credentials': typeof LayoutCredentialsRoute
  '/group_config': typeof LayoutGroup_configRoute
  '/groups': typeof LayoutGroupsRoute
  '/interfaces': typeof LayoutInterfacesRoute
  '/ip_interfaces': typeof LayoutIp_interfacesRoute
  '/items': typeof LayoutItemsRoute
  '/logs': typeof LayoutLogsRoute
  '/mac_addresses': typeof LayoutMac_addressesRoute
  '/settings': typeof LayoutSettingsRoute
  '/switches': typeof LayoutSwitchesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof LayoutAdminRoute
  '/arps': typeof LayoutArpsRoute
  '/credentials': typeof LayoutCredentialsRoute
  '/group_config': typeof LayoutGroup_configRoute
  '/groups': typeof LayoutGroupsRoute
  '/interfaces': typeof LayoutInterfacesRoute
  '/ip_interfaces': typeof LayoutIp_interfacesRoute
  '/items': typeof LayoutItemsRoute
  '/logs': typeof LayoutLogsRoute
  '/mac_addresses': typeof LayoutMac_addressesRoute
  '/settings': typeof LayoutSettingsRoute
  '/switches': typeof LayoutSwitchesRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/arps': typeof LayoutArpsRoute
  '/_layout/credentials': typeof LayoutCredentialsRoute
  '/_layout/group_config': typeof LayoutGroup_configRoute
  '/_layout/groups': typeof LayoutGroupsRoute
  '/_layout/interfaces': typeof LayoutInterfacesRoute
  '/_layout/ip_interfaces': typeof LayoutIp_interfacesRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/logs': typeof LayoutLogsRoute
  '/_layout/mac_addresses': typeof LayoutMac_addressesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/switches': typeof LayoutSwitchesRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/oauth-callback'
    | '/recover-password'
    | '/reset-password'
    | '/admin'
    | '/arps'
    | '/credentials'
    | '/group_config'
    | '/groups'
    | '/interfaces'
    | '/ip_interfaces'
    | '/items'
    | '/logs'
    | '/mac_addresses'
    | '/settings'
    | '/switches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/oauth-callback'
    | '/recover-password'
    | '/reset-password'
    | '/admin'
    | '/arps'
    | '/credentials'
    | '/group_config'
    | '/groups'
    | '/interfaces'
    | '/ip_interfaces'
    | '/items'
    | '/logs'
    | '/mac_addresses'
    | '/settings'
    | '/switches'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/oauth-callback'
    | '/recover-password'
    | '/reset-password'
    | '/_layout/admin'
    | '/_layout/arps'
    | '/_layout/credentials'
    | '/_layout/group_config'
    | '/_layout/groups'
    | '/_layout/interfaces'
    | '/_layout/ip_interfaces'
    | '/_layout/items'
    | '/_layout/logs'
    | '/_layout/mac_addresses'
    | '/_layout/settings'
    | '/_layout/switches'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/switches': {
      id: '/_layout/switches'
      path: '/switches'
      fullPath: '/switches'
      preLoaderRoute: typeof LayoutSwitchesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mac_addresses': {
      id: '/_layout/mac_addresses'
      path: '/mac_addresses'
      fullPath: '/mac_addresses'
      preLoaderRoute: typeof LayoutMac_addressesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/logs': {
      id: '/_layout/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LayoutLogsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ip_interfaces': {
      id: '/_layout/ip_interfaces'
      path: '/ip_interfaces'
      fullPath: '/ip_interfaces'
      preLoaderRoute: typeof LayoutIp_interfacesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/interfaces': {
      id: '/_layout/interfaces'
      path: '/interfaces'
      fullPath: '/interfaces'
      preLoaderRoute: typeof LayoutInterfacesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups': {
      id: '/_layout/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof LayoutGroupsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/group_config': {
      id: '/_layout/group_config'
      path: '/group_config'
      fullPath: '/group_config'
      preLoaderRoute: typeof LayoutGroup_configRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/credentials': {
      id: '/_layout/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof LayoutCredentialsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/arps': {
      id: '/_layout/arps'
      path: '/arps'
      fullPath: '/arps'
      preLoaderRoute: typeof LayoutArpsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutArpsRoute: typeof LayoutArpsRoute
  LayoutCredentialsRoute: typeof LayoutCredentialsRoute
  LayoutGroup_configRoute: typeof LayoutGroup_configRoute
  LayoutGroupsRoute: typeof LayoutGroupsRoute
  LayoutInterfacesRoute: typeof LayoutInterfacesRoute
  LayoutIp_interfacesRoute: typeof LayoutIp_interfacesRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutLogsRoute: typeof LayoutLogsRoute
  LayoutMac_addressesRoute: typeof LayoutMac_addressesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSwitchesRoute: typeof LayoutSwitchesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutArpsRoute: LayoutArpsRoute,
  LayoutCredentialsRoute: LayoutCredentialsRoute,
  LayoutGroup_configRoute: LayoutGroup_configRoute,
  LayoutGroupsRoute: LayoutGroupsRoute,
  LayoutInterfacesRoute: LayoutInterfacesRoute,
  LayoutIp_interfacesRoute: LayoutIp_interfacesRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutLogsRoute: LayoutLogsRoute,
  LayoutMac_addressesRoute: LayoutMac_addressesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSwitchesRoute: LayoutSwitchesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
